services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333" # REST
      - "6334:6334" # gRPC
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build: .
    container_name: fastapi_container
    env_file: .env
    environment:
      - QDRANT_HOST=qdrant
      - HOST=0.0.0.0
    depends_on:
      - qdrant
    ports:
      - "8000:8000"

volumes:
  qdrant_data:
